language: r
sudo: false
cache: packages
dist: trusty

r_binary_packages:
  - vegan
  - covr

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
    - _R_CHECK_TIMINGS_="0"
