init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github ropensci/rredlist

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

environment:
  global:
    R_CHECK_ARGS: "--no-build-vignettes --no-manual --as-cran"
  matrix:
    - R_VERSION: release
      R_ARCH: x64
      USE_RTOOLS: true
    - R_VERSION: devel
      R_ARCH: x64
      _R_CHECK_LENGTH_1_LOGIC2_: FALSE
      USE_RTOOLS: false

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: tar

  - path: '\*_*.zip'
    name: zip
